build:
  cuda_version: "12.1.1"
  python_packages:
    - "bitsandbytes==0.45.5"
    - "transformers==4.50.3"
    - "accelerate==1.6.0"
    - "scipy==1.15.2"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.27.1"
